apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: app-cm
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    env:
    - name: FIRSTNAME
      value: "Rakesh"
    command: ['sh', '-c', 'echo The app is running! && sleep 36000']
      
