apiVersion: v1
kind: Pod
metadata:
  name: redis2
  labels:
    app: demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd
  containers:
  - name: redis 
    image: redis 
    imagePullPolicy: IfNotPresent
