apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: ttype
                operator: In
                values:
                  - ssd
                  - hdd
  containers:
    - name: example-container
      image: example-image
