apiVersion: v1 
kind: Pod
metadata:
  name: memory-pod2
  labels:
    name: memory-pod2
    gpu: "True"
spec:
  containers:
  - name: stress
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi" 
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]