apiVersion: v1 
kind: Pod
metadata:
  name: memory-pod3
  labels:
    name: memory-pod3
    gpu: "True"
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi" 