apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: selfsubjectaccessreview-role
rules:
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectaccessreviews"]
    verbs: ["create"]
